name: Ejecuta dbt

on:
  workflow_dispatch:
#  schedule:
#    - cron: '55 */8 * * *'

jobs:
  transform:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: "pip" # caching pip dependencies
      - run: cd dbt-cf-project && pip install -r requirements.txt
      # Nuevo paso: Crear directorio de perfiles y generar profiles.yml dinÃ¡micamente
      - run: mkdir -p ~/.dbt
      - run: |
          cat > ~/.dbt/profiles.yml << EOF
          proyecto_001:
            target: prod
            outputs:
              prod:
                type: snowflake
                account: ${{ secrets.SNOWFLAKE_ACCOUNT }}
                user: ${{ secrets.SNOWFLAKE_USER }}
                password: ${{ secrets.SNOWFLAKE_PASSWORD }}
                database: ${{ secrets.SNOWFLAKE_DATABASE }}
                schema: ${{ secrets.SNOWFLAKE_SCHEMA }}
                warehouse: YOUR_WAREHOUSE  # Reemplaza con tu warehouse real en Snowflake
                role: YOUR_ROLE  # Reemplaza con tu role real en Snowflake, o omite si no es necesario
          EOF
      # Ejecutar dbt desde el directorio del proyecto
      - run: |
          cd dbt-cf-project
          dbt run -s "tag:codigo_facilito" -t prod
        env:
            SNOWFLAKE_USER: ${{ secrets.SNOWFLAKE_USER }}
            SNOWFLAKE_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD }}
            SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
            SNOWFLAKE_SCHEMA: ${{ secrets.SNOWFLAKE_SCHEMA }}
            SNOWFLAKE_DATABASE: ${{ secrets.SNOWFLAKE_DATABASE }}